/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calciatori;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import javax.swing.*;

/**
 *
 * @author sergi
 */
public class CalciatoriForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalciatoriForm.class.getName());

    /**
     * Creates new form CalciatoriForm
     */
    
    private ManagerCalciatore m;
    private JPanel interfaccia;
    private JScrollPane scrollPane;
        
    public CalciatoriForm() throws IOException{
        initComponents();
        
        SegnoZodiacale.aggiungiSegni(FileManager.leggiSegni("zodiaco.csv"));
        m = new ManagerCalciatore(FileManager.leggiCalciatori("sportivi.csv"));
        m.calcolaGoal();
        
        
        this.setLayout(new BorderLayout());
        
        interfaccia = new LayoutCalciatori(m.getCalciatori());
        scrollPane = new JScrollPane(interfaccia);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        this.add(scrollPane, BorderLayout.CENTER);
        
        this.setSize(new Dimension(1200, 600));
        
        this.addComponentListener(new ComponentAdapter(){
            @Override
            public void componentResized(ComponentEvent e){
                resizeLabelFont(interfaccia);
            }
        });
        
        JButton bottone = new JButton("Cambia intefaccia");
        bottone.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                cambiaInterfaccia();
            }
        });
        
        JButton bottoneIstruzioni = new JButton("Istruzioni");
        bottoneIstruzioni.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                mostraIstruzioni();
            }
        });
        
        bottone.setPreferredSize(new Dimension(300, 40));
        bottoneIstruzioni.setPreferredSize(new Dimension(300, 40));
        
        JPanel p = new JPanel();
        p.setLayout(new GridLayout(1,2));
        p.add(bottone);
        p.add(bottoneIstruzioni);
        p.setBorder(BorderFactory.createEmptyBorder(10,0,0,0));
        this.add(p, BorderLayout.SOUTH);
    }

    
    private void resizeLabelFont(Container container) {
        int windowWidth = getWidth();
        int windowHeight = getHeight();

        int fontSize = (int) (Math.min(windowWidth, windowHeight)*0.03);
        
        for(Component c : container.getComponents()){
            if(c instanceof JLabel)
                c.setFont(new Font("Arial", Font.BOLD, fontSize));
            else if(c instanceof Container)
                resizeLabelFont((Container) c);
            
        }
    }
    
    private void cambiaInterfaccia(){
        if(interfaccia instanceof LayoutCalciatori)
            interfaccia = new LayoutSegni(ManagerOutput.getOutput(m.getMappaSegni()));
        else
            interfaccia = new LayoutCalciatori(m.getCalciatori());
        
        scrollPane.setViewportView(interfaccia); // ← this actually swaps the panel
        scrollPane.revalidate();
        scrollPane.repaint();
        resizeLabelFont(interfaccia);
    }
    
    private void mostraIstruzioni(){
    String msg = """
                 Questo progetto vuole dimostrare un rapporto tra lo zodiaco e la bravura a calcio.
                 La prima interfaccia mostra le caratteristiche di ogni calciatore, preso da un file esterno.
                 La seconda interfaccia mostra un istogramma che indica il rapporto dei goal tra i vari segni zodiacali.                    
                 """;
    
        JLabel label = new JLabel("<html>" + msg.replace("\n", "<br>") + "</html>");
        label.setFont(new Font("Arial", Font.PLAIN, 18));

        JOptionPane.showMessageDialog(this, label, "Istruzioni", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
