/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calciatori;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.*;

/**
 *
 * @author sergi
 */
public class CalciatoriForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalciatoriForm.class.getName());

    /**
     * Creates new form CalciatoriForm
     */
    
    ManagerCalciatore m;
    
        
    public CalciatoriForm() throws IOException{
        initComponents();
        
        SegnoZodiacale.aggiungiSegni(FileManager.leggiSegni("zodiaco.csv"));
        m = new ManagerCalciatore(FileManager.leggiCalciatori("sportivi.csv"));
        m.calcolaGoal();
        
        this.addComponentListener(new ComponentAdapter(){
            @Override
            public void componentResized(ComponentEvent e){
                resizeLabelFont();
            }
        });
        this.setLayout(new GridBagLayout());
        
        this.creaInterfaccia(ManagerOutput.getOutput(m.getMappaSegni()));
        
        this.setSize(new Dimension(900, 600));
    }
    
    public void creaInterfaccia(LinkedHashMap<String, Integer> mappa){
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 0, 5, 10); // spacing between components
        gbc.weighty = 1.0;
        gbc.gridy = -1;
        int counter = 0;
        
        for(Map.Entry<String, Integer> set : mappa.entrySet()){
            JLabel label = new JLabel();
            JProgressBar progressbar = new JProgressBar();
            
            gbc.gridy++;
            
            gbc.gridx = 0;
            gbc.weightx = 0.25;
            this.add(label, gbc);

            gbc.gridx = 1;
            gbc.weightx = 0.75;
            this.add(progressbar, gbc);
            
            label.setText(set.getKey());
            label.setHorizontalAlignment(JLabel.CENTER);
            progressbar.setValue(set.getValue());
        }
    }
    
    private void resizeLabelFont() {
        int windowWidth = getWidth();
        int windowHeight = getHeight();

        // Base the font size on a fraction of the smaller dimension
        int fontSize = (int) (Math.min(windowWidth, windowHeight)*0.05);
        
        for(Component c : this.getContentPane().getComponents()){
            if(c instanceof JLabel)
                SwingUtilities.invokeLater(()->{c.setFont(new Font("Arial", Font.BOLD, fontSize));});
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
